endpoints:
  enabled: false
  health:
    enabled: true
  jmx:
    domain: bet
spring:
  mvc:
    favicon:
      enabled: false
  profiles:
    active: live, livefeed-apisports
  session:
    store-type: None
    timeout: 0
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      hibernate.cache.use_query_cache: true
      net.sf.ehcache.configurationResourceName: /bet-ehcache.xml
      hibernate.generate_statistics: false
  datasource:
    url: jdbc:postgresql://localhost:5432/bet
    username: bet
    password: bet
    driver-class-name: org.postgresql.Driver
  jackson:
    serialization: 
      WRITE_DATES_AS_TIMESTAMPS: false
      write-dates-as-timestamps: false
project_code: BET_DEVELOPMENT
flyway:
    enabled: false
    table: db_migration_history
    sqlMigrationSuffix: .Final.sql
    schemas: bet
    outOfOrder: true
    initOnMigrate: true
management:
  add-application-context-header: false
application:
    swaggerHost: localhost:8080
    timezone: Europe/Athens
    encryptKey: 1234567890qwertyuiopasdf
    currentMatchDays: 4
    allowedMatchDays:
    betDeadline:
    live_feed:
      interval: 300000
      footballapiorg:
        url: http://localhost:8000/games_new.json
#       url: http://api.football-data.org/v1/competitions/467/fixtures
        token:
      fifacom:
              url: http://localhost:8000/live.json
              competition: 2018 FIFA World Cup
      livescorescom:
              url: http://www.livescores.com/soccer/%s/
      apisports:
              url: https://v3.football.api-sports.io/fixtures?league=1&season=2022&date=%s
#              url: http://localhost:8000/apisports_games.json
              token:
      scorespro:
              url: https://www.scorespro.com/rss2/live-soccer.xml
    database-schema: bet
    email:
      username: X
      password: X
    rss_feed: https://www.espn.com/espn/rss/soccer/news,https://api.foxsports.com/v2/content/optimized-rss?partnerKey=MB0Wehpmuj2lUhuRhQaafhBjAJqaPU244mlTDK1i&size=30&tags=soccer/wc/league/12
    node:
         state-write-interval-mins: 30
         list-read-interval-secs: 1
