endpoints:
  enabled: false
  health:
    enabled: true
  jmx:
    domain: bet
spring:
  mvc:
    favicon:
      enabled: false
  profiles:
    active: live, lifefeed-footballapiorg
  session:
    store-type: None
    timeout: 1800   
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      hibernate.cache.use_query_cache: true
      net.sf.ehcache.configurationResourceName: /bet-ehcache.xml
      hibernate.generate_statistics: false
  datasource:
    url: jdbc:postgresql://dkoukis:5432/bet
    username: postgres
    password: upstream
    driver-class-name: org.postgresql.Driver
  jackson:
    serialization: 
      WRITE_DATES_AS_TIMESTAMPS: false
      write-dates-as-timestamps: false
project_code: BET_DEVELOPMENT
flyway:
    enabled: false
    table: db_migration_history
    sqlMigrationSuffix: .Final.sql
    schemas: bet
    outOfOrder: true
    initOnMigrate: true
management:
  add-application-context-header: false
application:
    timezone: Europe/Athens
    encryptKey: 1234567890qwertyuiopasdf
    allowedMatchDays: 1,2,3
    betDeadline: Wednesday, June 13 15:00
    live_feed:
      interval: 300000
      footballapiorg:
        url: http://localhost:8000/games.json
#       url: http://api.football-data.org/v1/competitions/467/fixtures
        token: X
      fifacom:
              url: http://localhost:8000/live.json
              competition: 2018 FIFA World Cup
      #       url: http://data.fifa.com/livescores/live/matches
    database-schema: bet
    email:
      username: X
      password: X
    rss_feed: http://www.fifa.com/worldcup/news/rss.xml, http://www.espnfc.com/fifa-world-cup/4/rss, https://www.uefa.com/rssfeed/worldcup/rss.xml
    node:
         state-write-interval-mins: 30
         list-read-interval-secs: 1